apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3200  # Ensure this URL matches your Tempo service in docker-compose.yml
    access: proxy
    isDefault: false
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
