receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"   # Accept gRPC traffic on all network interfaces
      http:
        endpoint: "0.0.0.0:55681"  # (Optional) Accept HTTP traffic on all interfaces

exporters:
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true  # Move 'insecure' under 'tls'

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
